version: '3.4'

services:

  db:
    image: mysql:5.7
    env_file:
      - php/.env
    environment:
      TZ: Europe/Moscow
    hostname: db
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306

  php:
    build:
      context: build
      dockerfile: php
      args:
        PHP_VERSION: 7.3
        PHP_EXTENSIONS: "common curl intl mbstring zip bcmath fpm mysql xml"
      target: php
    env_file:
      - php/.env
    hostname: php
    volumes:
      - ../shurisu:/project:cached
      - ./php/packages:/packages:cached
      - ~/.composer:/usr/local/share/composer:cached
    links:
      - db
    depends_on:
      - db

  web:
    build:
      context: build
      dockerfile: web
    env_file:
      - web/.env
    hostname: web
    ports:
      - 80:80
    volumes:
      - ../shurisu:/project:cached
    links:
      - php
    depends_on:
      - php

volumes:
  mysql: